### ISSUE TITLE
Add support for '3bd6970081b1fe451f878031c152211a4b' token

### ISSUE THREAD

**Issue by samuelb97** [PeculiarVentures/fortify#170]
Reader name: HID Global OMNIKEY 3x21 Smart Card Reader 0
ATR: 3BD6970081B1FE451F878031C152211A4B

```js
{
   "cards": [{
   	"atr": "3BD6970081B1FE451F878031C152211A4B",
   	"name": "Token name",
   	"driver": "6492CF0E9BEEAC65A05941FD6C22C6E53EFA9E62"
   }],
   "drivers": [{
   	"id": "6492CF0E9BEEAC65A05941FD6C22C6E53EFA9E62",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BD6970081B1FE451F878031C152211A4B](https://smartcard-atr.appspot.com/parse?ATR=3BD6970081B1FE451F878031C152211A4B)

**Comment by samuelb97** [comment]
It is a PIV-I card

**Comment by rmhrisk** [comment]
Thanks @samuelb97 it should work with the sample cards.json info above.

Would you mind testing it?
- Open file ~/.fortify/card.json
- Add your card to "cards" array
- Restart Fortify

Also what kind of PIV-I card?

**Comment by samuelb97** [comment]
Its a PIV-Interoperable smart card. I added the card but the token for the driver changes as I get the same error. Where would I find the pkcs11.dll file?

**Comment by rmhrisk** [comment]
We try to name the cards we support so people can know what’s been tested to work. Do you know the make and model of this card?

As for where the P11 can be found, I am presuming based on your description so far that the P11 listed in the cards.json file with the id of 993988460d8f49a2ac519a2935f11533

Will work with the card, without more details though I’m just guessing.

As for it not working, please provide a log file.

**Comment by samuelb97** [comment]
I set the driver to the open-sc one you mentioned. Got a different error saying it could not find my open-sc-pksc11.dll fil but the path is right. Thank you for the help


**Log**

{"message":"Application started at Tue Jun 25 2019 00:55:58 GMT-0400 (Eastern Daylight Time)","level":"info"}
{"message":"OS win32 ia32 ","level":"info"}
{"message":"Fortify v1.0.19","level":"info"}
{"message":"System locale is 'en-US'","level":"info"}
{"message":"Locale: Set language to 'en'","level":"info"}
{"message":"Fortify: Create window index","level":"info"}
{"message":"Update: Check for new update","level":"info"}
{"message":"Update: New version wasn't found","level":"info"}
{"message":"SSL certificate is loaded","level":"info"}
{"message":"Comparing current version of card.json file with remote","level":"info"}
{"message":"card.json has the latest version","level":"info"}
{"message":"Server: Started at 127.0.0.1:31337","level":"info"}
{"message":"Provider: Add crypto 'Windows CryptoAPI' 205a891e4d00c2420dcd093593dcf12b95d32a16","level":"info"}
{"message":"Provider:AddCrypto: PKCS#11 'C:\\Program Files (x86)\\Fortify\\pvpkcs11.dll' 'C:\\Program Files (x86)\\Fortify\\pvpkcs11.dll'","level":"info"}
{"message":"Provider: Add crypto 'NSS Certificate DB' a7370eae6951997646c5bfedf8f3df0d8b8b698d","level":"info"}
{"message":"Provider:AddCrypto: PKCS#11 'softokn3.dll' 'softokn3.dll'","level":"info"}
{"message":"Provider:Opened","level":"info"}
{"message":"PCSCWatcher: New reader detected HID Global OMNIKEY 3x21 Smart Card Reader 0","level":"info"}
{"message":"PCSCWatcher: New reader detected HID Global OMNIKEY 3x21 Smart Card Reader 0","level":"info"}
{"message":"PCSCWatcher:Insert reader:'HID Global OMNIKEY 3x21 Smart Card Reader 0' ATR:3bd6970081b1fe451f878031c152211a4b","level":"info"}
{"message":"PCSCWatcher:Insert reader:'HID Global OMNIKEY 3x21 Smart Card Reader 0' ATR:3bd6970081b1fe451f878031c152211a4b","level":"info"}
{"message":"Provider:Token:Insert reader:'HID Global OMNIKEY 3x21 Smart Card Reader 0' name:'FTI: PIV-I Card' atr:3bd6970081b1fe451f878031c152211a4b","level":"info"}
{"message":"WebCryptoLocalError: C:\\windows\\System32\\opensc-pkcs11.dll\n    at new WebCryptoLocalError (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:338:23)\n    at LocalProvider.onTokenInsert (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2041:33)\n    at CardWatcher.emit (events.js:182:13)\n    at PCSCWatcher.CardWatcher.watcher.on.on.on (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:860:26)\n    at PCSCWatcher.emit (events.js:182:13)\n    at Timeout.setTimeout [as _onTimeout] (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:673:38)\n    at ontimeout (timers.js:425:11)\n    at tryOnTimeout (timers.js:289:5)\n    at listOnTimeout (timers.js:252:5)\n    at Timer.processTimers (timers.js:212:10)","level":"error"}
{"message":"Fortify: Create window message","level":"info"}
{"message":"Provider:Token:Remove reader:'HID Global OMNIKEY 3x21 Smart Card Reader 0' name:'FTI: PIV-I Card' atr:3bd6970081b1fe451f878031c152211a4b","level":"info"}
{"message":"WebCryptoLocalError: Provider:Token:Remove PKCS#11 lib C:\\windows\\System32\\opensc-pkcs11.dll. Win32 error 126\n    at Error (native) PKCS11::Load:136\n    at new WebCryptoLocalError (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:338:23)\n    at card.libraries.forEach (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2157:40)\n    at Array.forEach (<anonymous>)\n    at LocalProvider.onTokenRemove (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2134:28)\n    at CardWatcher.emit (events.js:182:13)\n    at PCSCWatcher.CardWatcher.watcher.on.on.on.on (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:888:26)\n    at PCSCWatcher.emit (events.js:182:13)\n    at CardReader.reader.on (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:659:38)\n    at CardReader.emit (events.js:182:13)\n    at C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\pcsclite\\lib\\pcsclite.js:68:23","level":"error"}
{"message":"WebCryptoLocalError: TOKEN_REMOVE_NO_SLOTS_FOUND\n    at new WebCryptoLocalError (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:338:23)\n    at LocalProvider.onTokenRemove (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2161:36)\n    at CardWatcher.emit (events.js:182:13)\n    at PCSCWatcher.CardWatcher.watcher.on.on.on.on (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:888:26)\n    at PCSCWatcher.emit (events.js:182:13)\n    at CardReader.reader.on (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:659:38)\n    at CardReader.emit (events.js:182:13)\n    at C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\pcsclite\\lib\\pcsclite.js:68:23","level":"error"}
{"message":"PCSCWatcher:Insert reader:'HID Global OMNIKEY 3x21 Smart Card Reader 0' ATR:3bd6970081b1fe451f878031c152211a4b","level":"info"}
{"message":"PCSCWatcher:Insert reader:'HID Global OMNIKEY 3x21 Smart Card Reader 0' ATR:3bd6970081b1fe451f878031c152211a4b","level":"info"}
{"message":"Provider:Token:Insert reader:'HID Global OMNIKEY 3x21 Smart Card Reader 0' name:'FTI: PIV-I Card' atr:3bd6970081b1fe451f878031c152211a4b","level":"info"}
{"message":"WebCryptoLocalError: C:\\windows\\System32\\opensc-pkcs11.dll\n    at new WebCryptoLocalError (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:338:23)\n    at LocalProvider.onTokenInsert (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2041:33)\n    at CardWatcher.emit (events.js:182:13)\n    at PCSCWatcher.CardWatcher.watcher.on.on.on (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:860:26)\n    at PCSCWatcher.emit (events.js:182:13)\n    at Timeout.setTimeout [as _onTimeout] (C:\\Program Files (x86)\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:673:38)\n    at ontimeout (timers.js:425:11)\n    at tryOnTimeout (timers.js:289:5)\n    at listOnTimeout (timers.js:252:5)\n    at Timer.processTimers (timers.js:212:10)","level":"error"}
{"message":"Fortify: Create window message","level":"info"}

**Comment by microshine** [comment]
Are you sure that OpenSC supports this card?
I found only 2 ATRs in OpenSC source code which starts with "3b:d6"
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-asepcos.c#L41-L42

Can you try opensc-tools for your card getting?

**Comment by microshine** [comment]
Do you see certificates from your card in My storage from `certmgr.msc`? Fortify uses Windows API `crypt32.dll` for card reading but it doesn't support CSP providers

**Comment by samuelb97** [comment]
I can see my certificates for the card in the certmgr.msc.

When I use the opensc-tools, I can see the card but get error finding files?

<img width="409" alt="OpenSC feedback" src="https://user-images.githubusercontent.com/30537308/60156829-5f983580-97bb-11e9-877b-6c6d96d952a8.PNG">
