### ISSUE TITLE
Fortify build is failing (tried on both windows as well as macOS machine)

### ISSUE THREAD

**Issue by devilmightcry** [PeculiarVentures/fortify#323]
I am trying to build the latest 'master'.

The README.md is not very clear about the steps, have few queries:
1. Regarding the "Note" in `npm install` steps, do we have to modify the `.npmrc` file with `openssl_dir` parameter providing the openSSL location (openSSL executable path) ?
2. Which version of openSSL is recommended ?

**Windows:** Building on Windows10, the console logs during build are pasted below:

ERROR in [at-loader] ./src/main/ssl.ts:221:48
    TS2345: Argument of type 'CryptoKey | CryptoKeyPair' is not assignable to parameter of type 'CryptoKeyPair'.
  Type 'CryptoKey' is missing the following properties from type 'CryptoKeyPair': privateKey, publicKey

ERROR in [at-loader] ./src/main/ssl.ts:224:51
    TS2345: Argument of type 'CryptoKey | CryptoKeyPair' is not assignable to parameter of type 'CryptoKeyPair'.
  **Type 'CryptoKey' is not assignable to type 'CryptoKeyPair'.**

ERROR in [at-loader] ./src/main/ssl.ts:224:75
    TS2339: Property 'privateKey' does not exist on type 'CryptoKey | CryptoKeyPair'.
  Property 'privateKey' does not exist on type 'CryptoKey'.

ERROR in [at-loader] ./src/main/ssl.ts:225:54
    TS2339: Property 'privateKey' does not exist on type 'CryptoKey | CryptoKeyPair'.
  Property 'privateKey' does not exist on type 'CryptoKey'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! fortify@1.0.22 build:prod: `webpack --config webpack.config.js -p`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the fortify@1.0.22 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abhishek.mishra\AppData\Roaming\npm-cache\_logs\2020-05-24T16_36_24_588Z-debug.log
Error: Command finished with code 2
    at ChildProcess.<anonymous> (C:\fortify\scripts\build\utils.ts:87:24)
    at ChildProcess.emit (events.js:310:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fortify@1.0.22 build: `ts-node scripts/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fortify@1.0.22 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abhishek.mishra\AppData\Roaming\npm-cache\_logs\2020-05-24T16_36_24_656Z-debug.log

**macOS:** Building on macOS Mojave, I am getting similar issue as (https://github.com/PeculiarVentures/fortify/issues/321)

Please suggest if I am going on the wrong path ?

**Comment by devilmightcry** [comment]
Update:

On Windows, I moved forward a bit, however now the error is similar as on macOS. Build is failing at AI set new version v1.0.22:

Run command: AI set new version v1.0.22
  C:\Program Files (x86)\Caphyon\Advanced Installer 15.6\bin\x86\AdvancedInstaller.com /edit C:\Users\abhishek.mishra\Documents\Fortify_x64.aip /SetVersion 1.0.22

**File not found: "C:\Users\abhishek.mishra\Documents\Fortify_x64.aip".**
Error: Command finished with code 4294967295
    at ChildProcess.<anonymous> (C:\fortify\scripts\build\utils.ts:39:18)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fortify@1.0.22 build: `ts-node scripts/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fortify@1.0.22 build script.

**Comment by devilmightcry** [comment]
Will wait for next release to see if the issues are fixed.
