### ISSUE TITLE
Error on IDPrime card removing

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify#421]
Maybe IDPrime crashes SCARD services and Widnows restarts that service again. But Fortify's PCSC service doesn't work after that.

### Windows codes

Code | Description
| -- | -- | 
SCARD_E_SERVICE_STOPPED<br/>0x8010001E | The smart card resource manager has shut down.
SCARD_E_NO_SERVICE<br/>0x8010001D | The smart card resource manager is not running.

### Log
```
error: [server]  Server event error {"error":"Cannot find removed slot in PKCS#11 library C:\\Program Files (x86)\\Gemalto\\IDGo 800 PKCS#11\\IDPrimePKCS11.dll. Win32 error 193","stack":"so: Cannot find removed slot in PKCS#11 library C:\\Program Files (x86)\\Gemalto\\IDGo 800 PKCS#11\\IDPrimePKCS11.dll. Win32 error 193
    at new so (main.js:279:76612)
    at Zo.onTokenRemove (main.js:279:114683)
    at Ho.emit (events.js:315:20)
    at Ho.emit (main.js:254:223804)
    at Ho.emit (main.js:279:100011)
    at qo.<anonymous> (main.js:279:99905)
    at qo.emit (events.js:315:20)
    at qo.emit (main.js:254:223804)
    at qo.emit (main.js:279:99065)
    at CardReader.<anonymous> (main.js:279:98815)"}
error: [server]  Server event error {"error":"SCardListReaders error: Le gestionnaire de ressources des cartes ´┐¢ puce s´┐¢est arr´┐¢t´┐¢.\r\n(0x8010001e)","stack":"Error: SCardListReaders error: Le gestionnaire de ressources des cartes ´┐¢ puce s´┐¢est arr´┐¢t´┐¢.\r\n(0x8010001e)"}
error: [server]  Server event error {"error":"SCardListReaders error: Le gestionnaire de ressources des cartes ´┐¢ puce s´┐¢est arr´┐¢t´┐¢.\r\n(0x8010001e)","stack":"Error: SCardListReaders error: Le gestionnaire de ressources des cartes ´┐¢ puce s´┐¢est arr´┐¢t´┐¢.\r\n(0x8010001e)"}
error: [server]  Server event error {"error":"SCardListReaders error: Le gestionnaire de ressources des cartes ´┐¢ puce n´┐¢est pas en cours d´┐¢ex´┐¢cution.\r\n(0x8010001d)","stack":"Error: SCardListReaders error: Le gestionnaire de ressources des cartes ´┐¢ puce n´┐¢est pas en cours d´┐¢ex´┐¢cution.\r\n(0x8010001d)"}
error: [server]  Server event error {"error":"Cannot find removed slot in PKCS#11 library C:\\Program Files\\Gemalto\\IDGo 800 PKCS#11\\IDPrimePKCS1164.dll. Win32 error 126","stack":"so: Cannot find removed slot in PKCS#11 library C:\\Program Files\\Gemalto\\IDGo 800 PKCS#11\\IDPrimePKCS1164.dll. Win32 error 126
    at new so (main.js:279:76612)
    at Zo.onTokenRemove (main.js:279:114683)
    at Ho.emit (events.js:315:20)
    at Ho.emit (main.js:254:223804)
    at Ho.emit (main.js:279:100011)
    at qo.<anonymous> (main.js:279:99905)
    at qo.emit (events.js:315:20)
    at qo.emit (main.js:254:223804)
    at qo.emit (main.js:279:99065)
    at CardReader.<anonymous> (main.js:279:98815)"}
```

**Comment by microshine** [comment]
`pcsclite` closes session on `error` event.

I see 2 ways to solve that:
- Review `pcsclite` and fix it
- Reinit pcsc instance on each error (but we need to be sure that each error closes the session)

**Comment by rmhrisk** [comment]
There will always be some errors. I think you need to do:
* Reinit pcsc instance on each error (but we need to be sure that each error closes the session)
