### ISSUE TITLE
Error on key generation

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify#422]
Token: IDPrime
OS: Windows
Version: 1.8.1

### Log
```
{
  "source": "server",
  "error": "Rsa: Can not generate new key CKR_ATTRIBUTE_TYPE_INVALID:18
    at Error (native) PKCS11::C_GenerateKeyPair:929",
  "stack": "Error: Rsa: Can not generate new key CKR_ATTRIBUTE_TYPE_INVALID:18
    at Error (native) PKCS11::C_GenerateKeyPair:929
    at main.js:281:51075
    at main.js:256:302351",
  "level": "error",
  "message": "Server event error",
  "timestamp": "2021-06-28T16:00:49.707Z"
}
```

**Comment by microshine** [comment]
Fortify adds sensitive flag to public key template
```js
{
  id: <Buffer e7 9e 87 22 95 95 0f ba 47 e8 ba 48 db e6 cb bf 5d 09 07 08>,
  sensitive: true,
  token: true,
  label: 'RSA',
  verify: true,
  class: 2,
  private: false,
  keyType: 0,
  publicExponent: <Buffer 01 00 01>,
  modulusBits: 2048
}
```

**Comment by microshine** [comment]
`@webcrypto-local/server@1.6.5` fixes this issue
