### ISSUE TITLE
Fortify startup error in Ubuntu

### ISSUE THREAD

**Issue by alimodev** [PeculiarVentures/fortify#436]
When I open Fortify in Ubuntu Linux, it says: "It looks like the `Smart Card Resource Manager` is not running. please start this service and start Fortify again."

Also when I open https://tools.fortifyapp.com/ in Firefox, it says: "Unfortunately, your browser doesn't allow connections to localhost. Please try a different browser". In Chrome it says: "Server is offline. Wait until the connection is established"

How can I start "Smart Card Resource Manager"?

**Comment by alimodev** [comment]
Here is the Log after installing libnss3-tools (sudo apt-get install libnss3-tools)

```
{"source":"application","time":"2021-10-11T22:22:46.865Z","level":"info","message":"Starting","timestamp":"2021-10-11T22:22:46.870Z"}
{"source":"application","version":"1.8.2","versionChrome":"87.0.4280.141","versionElectron":"11.4.7","versionNode":"12.18.3","level":"info","message":"Application info","timestamp":"2021-10-11T22:22:46.871Z"}
{"source":"system","type":"Linux","platform":"linux","arch":"x64","cpus":4,"version":"5.13.0-7614-generic","totalmem":8338837504,"freemem":4388839424,"level":"info","message":"System info","timestamp":"2021-10-11T22:22:46.891Z"}
{"source":"system","width":1600,"height":900,"level":"info","message":"Screen size","timestamp":"2021-10-11T22:22:47.096Z"}
{"source":"l10n","lang":"en","level":"info","message":"Change language","timestamp":"2021-10-11T22:22:47.097Z"}
{"source":"ssl-service","status":"valid","level":"info","message":"Get certificate status","timestamp":"2021-10-11T22:22:47.120Z"}
{"source":"nss","command":"\"certutil\" -L -d \"sql:/home/user/.mozilla/firefox/1r641hy8.default\" -h \"all\"","shell":"bash","level":"info","message":"Run certutil command","timestamp":"2021-10-11T22:22:47.122Z"}
{"source":"ssl-installer","error":"Command failed: \"certutil\" -L -d \"sql:/home/user/.mozilla/firefox/1r641hy8.default\" -h \"all\"\ncertutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.\n","stack":"Error: Command failed: \"certutil\" -L -d \"sql:/home/user/.mozilla/firefox/1r641hy8.default\" -h \"all\"\ncertutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.\n\n    at checkExecSyncError (child_process.js:639:11)\n    at Object.execSync (child_process.js:675:15)\n    at Object.execSync (electron/js2c/asar_bundle.js:5:12008)\n    at t.NssCertUtils.run (/opt/Fortify/resources/app.asar/out/main.js:256:201543)\n    at t.NssCertUtils.list (/opt/Fortify/resources/app.asar/out/main.js:256:200991)\n    at t.NssCertUtils.exists (/opt/Fortify/resources/app.asar/out/main.js:256:200732)\n    at t.SslCertInstaller.installFirefox (/opt/Fortify/resources/app.asar/out/main.js:256:180038)\n    at g.run (/opt/Fortify/resources/app.asar/out/main.js:256:175390)\n    at t.Server.init (/opt/Fortify/resources/app.asar/out/main.js:31:552664)\n    at b.initServer (/opt/Fortify/resources/app.asar/out/main.js:172:90344)","level":"error","message":"SSL install error","timestamp":"2021-10-11T22:22:47.148Z"}
{"source":"nss","command":"\"certutil\" -L -d \"sql:/home/user/.mozilla/firefox/mnrpoc6b.default-release\" -h \"all\"","shell":"bash","level":"info","message":"Run certutil command","timestamp":"2021-10-11T22:22:47.149Z"}
{"source":"nss","command":"\"certutil\" -L -d \"sql:/home/user/.mozilla/firefox/mnrpoc6b.default-release\" -n \"Fortify Local CA\" -a \"\"","shell":"bash","level":"info","message":"Run certutil command","timestamp":"2021-10-11T22:22:47.197Z"}
{"source":"server","level":"info","message":"SSL certificate is loaded","timestamp":"2021-10-11T22:22:47.227Z"}
{"source":"server","level":"info","message":"Comparing current version of card.json file with remote","timestamp":"2021-10-11T22:22:47.228Z"}
{"source":"server","version":"1.1.3","level":"info","message":"card.json has the latest version","timestamp":"2021-10-11T22:22:47.779Z"}
{"source":"pcsc","level":"info","message":"Start PCSC listening","timestamp":"2021-10-11T22:22:47.787Z"}
{"source":"server","error":"PCSC_CANNOT_START","stack":"so: PCSC_CANNOT_START\n    at new so (/opt/Fortify/resources/app.asar/out/main.js:281:76612)\n    at qo.start (/opt/Fortify/resources/app.asar/out/main.js:281:98855)\n    at zo.start (/opt/Fortify/resources/app.asar/out/main.js:281:103158)\n    at uc.listen (/opt/Fortify/resources/app.asar/out/main.js:281:135504)\n    at t.Server.run (/opt/Fortify/resources/app.asar/out/main.js:31:555541)\n    at t.Server.init (/opt/Fortify/resources/app.asar/out/main.js:31:553238)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async b.initServer (/opt/Fortify/resources/app.asar/out/main.js:172:90326)\n    at async b.onReady (/opt/Fortify/resources/app.asar/out/main.js:172:89193)","level":"error","message":"Server event error","timestamp":"2021-10-11T22:22:47.788Z"}
{"source":"windows","name":"message","id":"warn.pcsc.cannot_start","level":"info","message":"Create window","timestamp":"2021-10-11T22:22:47.821Z"}
{"source":"update","level":"info","message":"Check for new update","timestamp":"2021-10-11T22:22:47.832Z"}
{"source":"application","time":"2021-10-11T22:22:47.832Z","duration":967,"level":"info","message":"Loaded","timestamp":"2021-10-11T22:22:47.833Z"}
{"source":"server","address":"127.0.0.1:31337","level":"info","message":"Started","timestamp":"2021-10-11T22:22:47.835Z"}
{"source":"provider","library":"/usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so","manufacturerId":"Mozilla Foundation","cryptokiVersion":{"major":2,"minor":20},"libraryVersion":{"major":3,"minor":49},"firmwareVersion":{"major":1,"minor":0},"level":"info","message":"PKCS#11 library information","timestamp":"2021-10-11T22:22:47.848Z"}
{"source":"provider","id":"8bbae6f98340d7a92006c21da65c1acd345ba946","library":"/usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so","name":"NSS Certificate DB","reader":"NSS User Private Key and Certificate Services","level":"info","message":"Crypto provider was added to the list","timestamp":"2021-10-11T22:22:47.849Z"}
{"source":"pcsc","level":"info","message":"Start PCSC listening","timestamp":"2021-10-11T22:22:47.855Z"}
{"source":"server","error":"PCSC_CANNOT_START","stack":"so: PCSC_CANNOT_START\n    at new so (/opt/Fortify/resources/app.asar/out/main.js:281:76612)\n    at qo.start (/opt/Fortify/resources/app.asar/out/main.js:281:98855)\n    at Ho.start (/opt/Fortify/resources/app.asar/out/main.js:281:100099)\n    at Zo.open (/opt/Fortify/resources/app.asar/out/main.js:281:111346)\n    at cc.open (/opt/Fortify/resources/app.asar/out/main.js:281:133089)\n    at po.<anonymous> (/opt/Fortify/resources/app.asar/out/main.js:281:134677)\n    at po.emit (events.js:315:20)\n    at po.emit (/opt/Fortify/resources/app.asar/out/main.js:256:223819)\n    at po.emit (/opt/Fortify/resources/app.asar/out/main.js:281:78457)\n    at /opt/Fortify/resources/app.asar/out/main.js:281:79436","level":"error","message":"Server event error","timestamp":"2021-10-11T22:22:47.856Z"}
{"source":"server","error":"PCSC_CANNOT_START","stack":"so: PCSC_CANNOT_START\n    at new so (/opt/Fortify/resources/app.asar/out/main.js:281:76612)\n    at qo.start (/opt/Fortify/resources/app.asar/out/main.js:281:98855)\n    at Ho.start (/opt/Fortify/resources/app.asar/out/main.js:281:100099)\n    at Zo.open (/opt/Fortify/resources/app.asar/out/main.js:281:111346)\n    at cc.open (/opt/Fortify/resources/app.asar/out/main.js:281:133089)\n    at po.<anonymous> (/opt/Fortify/resources/app.asar/out/main.js:281:134677)\n    at po.emit (events.js:315:20)\n    at po.emit (/opt/Fortify/resources/app.asar/out/main.js:256:223819)\n    at po.emit (/opt/Fortify/resources/app.asar/out/main.js:281:78457)\n    at /opt/Fortify/resources/app.asar/out/main.js:281:79436","level":"error","message":"Server event error","timestamp":"2021-10-11T22:22:47.866Z"}
{"source":"update","level":"info","message":"New version wasn't found","timestamp":"2021-10-11T22:22:48.359Z"}
{"source":"windows","name":"message","id":"warn.pcsc.cannot_start","level":"info","message":"Close window","timestamp":"2021-10-11T22:22:49.456Z"}
```

**Comment by alimodev** [comment]
After installing libpcsclite-dev and pcscd, now it opens without an error and I can access it in Firefox.

```
sudo apt-get install libusb-1.0-0-dev libpcsclite-dev pcscd pcsc-tools
```
