### ISSUE TITLE
CKR_SESSION_HANDLE_INVALID

### ISSUE THREAD

**Issue by Ottunger** [PeculiarVentures/fortify#473]
Hello,

We intermittently receive errors of CKR_SESSION_HANDLE_INVALID, do you have any idea what might cause it? We do not remove the card of the reader as we test ourselves, obviously.

```json
{"source":"server","session":"b29634846e82cb939781a591e4fe72112a9da422bb1e851d2bfc846f7a978839","action":"crypto/keyStorage/keys","provider":"c7c623c1a303104b6932ec25e824ed7ded13eaa824242f143508f9b6ee1d4a7f","level":"info","message":"Run action","timestamp":"2022-03-09T14:22:41.641Z"}
{"source":"server-api","crypto":"MCARD","level":"info","message":"keyStorage/keys","timestamp":"2022-03-09T14:22:41.642Z"}
{"source":"server","error":"CKR_SESSION_HANDLE_INVALID","level":"error","message":"Server event error","timestamp":"2022-03-09T14:22:41.643Z"}
{"source":"windows","name":"preferences","level":"info","message":"Create window","timestamp":"2022-03-09T14:22:50.479Z"}
{"source":"update","level":"info","message":"Check for new update","timestamp":"2022-03-09T14:22:50.943Z"}
{"source":"update","jwsLink":"[https://fortifyapp.com/packages/update.jws","error":"getaddrinfo](https://fortifyapp.com/packages/update.jws%22,%22error%22:%22getaddrinfo) ENOTFOUND fortifyapp.com","stack":"Error: getaddrinfo ENOTFOUND fortifyapp.com\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)","level":"error","message":"JWS GET error","timestamp":"2022-03-09T14:22:51.068Z"}
{"source":"update","error":"Unable to connect to update server","stack":"UpdateError: Unable to connect to update server\n at h.getJWS (C:\\Program Files\\Fortify\\resources\\app.asar\\out\\main.js:31:551404)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)\n at async h.getUpdateInfo (C:\\Program Files\\Fortify\\resources\\app.asar\\out\\main.js:31:551495)\n at async h.checkForUpdates (C:\\Program Files\\Fortify\\resources\\app.asar\\out\\main.js:31:551837)","level":"error","message":"Get info error","timestamp":"2022-03-09T14:22:51.068Z"}
{"source":"update","error":"Unable to connect to update server","stack":"UpdateError: Unable to connect to update server\n at h.getJWS (C:\\Program Files\\Fortify\\resources\\app.asar\\out\\main.js:31:551404)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)\n at async h.getUpdateInfo (C:\\Program Files\\Fortify\\resources\\app.asar\\out\\main.js:31:551495)\n at async h.checkForUpdates (C:\\Program Files\\Fortify\\resources\\app.asar\\out\\main.js:31:551837)","level":"error","message":"Update error","timestamp":"2022-03-09T14:22:51.068Z"}
```

Thanks!

**Comment by Ottunger** [comment]
I will try to get the logs of the provider DLL. I've seen this only that way.
Have to restart all processes and hope in such cases.

A point to note: we manually close sessions after business transactions some time!

**Comment by Ottunger** [comment]
I've checked the provider log and it contains some 0x80100002 but no called to ask for closing the session.
Have you ever experienced something like this?

Attached for reference!

```txt
[ INFO ](pkcs11) Creating slot 0 for reader Gemplus USB SmartCard Reader 0
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](pkcs11) Found supported card. Will try to load the token
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](token) Loading token
[ INFO ](token) Seeding token's RNG using card as entropy pool
[ INFO ](token) RNG seeded by using 32 bytes of entropy.
[ WARN ](card) Select failed
[ INFO ](token) EF.DIR: [{"SSCD" OID = 'A0:00:00:00:63:50:4B:43:53:2D:31:35' at 3F00DF02}, {"ICAO" OID = 'A0:00:00:02:47:10:01' at 3F00DF01}]
[ INFO ](token) EF.DIR SSCD entry: {"SSCD" OID = 'A0:00:00:00:63:50:4B:43:53:2D:31:35' at 3F00DF02}
[ INFO ](token) EF.DIR ICAO entry: {"ICAO" OID = 'A0:00:00:02:47:10:01' at 3F00DF01}
[ INFO ](card) Read 82 bytes file.
[ INFO ](token) EF.CardAccess: Card access [PaceInfo(0.4.0.127.0.7.2.2.4.2.1, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.2, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.3, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.4, V2, param id = 13)]
[ INFO ](pkcs11) This token is not authenticated and requires initial authentication. Will try to look in cache for it's CAN.
[ INFO ](ipc) Opening client memory segment
[ INFO ](ipc) Looking for cache object
[ INFO ](ipc) Constructed cache
[ INFO ](pkcs11) Cache entry for reader found (6 bytes).
[ INFO ](card) Preparing to peform PACE
[ INFO ](card) Preparing PACE environment for key ref 2 (CAN)
[ INFO ](card) PACE done with key ref 2
[ INFO ](card) Read 56 bytes file.
[ WARN ](token) Failed to parse file 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[ INFO ](token) EF.OD: []
[ INFO ](token) Assuming default EF.OD
[ INFO ](card) Read 8 bytes file.
[ WARN ](token) Failed to parse file 0000000000000000
[ INFO ](token) EF.CiaInfo: { manufacturer = "", label = "", serial number = }
[ INFO ](card) Read 92 bytes file.
[ INFO ](pkcs11) Detected private key to be 256 bit long.
[ INFO ](card) Read 92 bytes file.
[ INFO ](pkcs11) Detected private key to be 256 bit long.
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotInfo]
[ INFO ](pkcs11) [C_GetSlotInfo] = 0x00000000
[ WARN ](pkcs11) [C_Initialize] = 0x00000191 
[ INFO ](pkcs11) [C_GetInfo]
[ INFO ](pkcs11) [C_GetInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotInfo]
[ INFO ](pkcs11) [C_GetSlotInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](pkcs11) [C_OpenSession]
[ INFO ](pkcs11) Creating session 1024
[ INFO ](pkcs11) [C_OpenSession] = 0x00000000
[ INFO ](pkcs11) [C_GetSessionInfo]
[ INFO ](pkcs11) Session state = 0 flags: 6
[ INFO ](pkcs11) [C_GetSessionInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotInfo]
[ INFO ](pkcs11) [C_GetSlotInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetMechanismList]
[ INFO ](pkcs11) [C_GetMechanismList] = 0x00000000
[ INFO ](pkcs11) [C_GetMechanismList]
[ INFO ](pkcs11) [C_GetMechanismList] = 0x00000000
[ INFO ](pkcs11) [C_GetMechanismInfo]
[ INFO ](pkcs11) [C_GetMechanismInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetMechanismInfo]
[ INFO ](pkcs11) [C_GetMechanismInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetMechanismInfo]
[ INFO ](pkcs11) [C_GetMechanismInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ WARN ](pcsc) SCardGetStatusChange   RV = 0x80100002
[ INFO ](token) Certificate was removed from the Windwos store
[ INFO ](token) Certificate was removed from the Windwos store
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](ipc) Creating owner memory segment
[ INFO ](ipc) Constructed cache
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ WARN ](pcsc) SCardConnect           RV = 0x8010000b
[ WARN ](pcsc) SCardConnect           RV = 0x80100069
[ INFO ](token) Loading token
[ INFO ](token) Seeding token's RNG using card as entropy pool
[ WARN ](pcsc) Card is invalid (not connected)
[ WARN ](card) Transmission failed
[ WARN ](token) Failed to seed token's RNG using card's entropy: Transmission of command failed
[ WARN ](pcsc) Card is invalid (not connected)
[ WARN ](card) Transmission failed
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](token) Loading token
[ INFO ](token) Seeding token's RNG using card as entropy pool
[ INFO ](token) RNG seeded by using 32 bytes of entropy.
[ WARN ](card) Select failed
[ INFO ](token) EF.DIR: [{"SSCD" OID = 'A0:00:00:00:63:50:4B:43:53:2D:31:35' at 3F00DF02}, {"ICAO" OID = 'A0:00:00:02:47:10:01' at 3F00DF01}]
[ INFO ](token) EF.DIR SSCD entry: {"SSCD" OID = 'A0:00:00:00:63:50:4B:43:53:2D:31:35' at 3F00DF02}
[ INFO ](token) EF.DIR ICAO entry: {"ICAO" OID = 'A0:00:00:02:47:10:01' at 3F00DF01}
[ INFO ](card) Read 82 bytes file.
[ INFO ](token) EF.CardAccess: Card access [PaceInfo(0.4.0.127.0.7.2.2.4.2.1, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.2, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.3, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.4, V2, param id = 13)]
[ INFO ](card) Preparing to peform PACE
[ INFO ](card) Preparing PACE environment for key ref 2 (CAN)
[ INFO ](card) PACE done with key ref 2
[ INFO ](card) Read 56 bytes file.
[ WARN ](token) Failed to parse file 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[ INFO ](token) EF.OD: []
[ INFO ](token) Assuming default EF.OD
[ INFO ](card) Read 8 bytes file.
[ WARN ](token) Failed to parse file 0000000000000000
[ INFO ](token) EF.CiaInfo: { manufacturer = "", label = "", serial number = }
[ INFO ](card) Read 92 bytes file.
[ INFO ](pkcs11) Detected private key to be 256 bit long.
[ INFO ](card) Read 92 bytes file.
[ INFO ](pkcs11) Detected private key to be 256 bit long.
[ INFO ](card) Read 1225 bytes file.
[ INFO ](card) Read 1250 bytes file.
[ INFO ](token) Registering certificate
[ INFO ](token) provider: Microsoft Base Smart Card Crypto Provider
[ INFO ](token) container: ae6d5874-8e73-420b-9574-fb50e9afed0e
[ INFO ](token) Certificate was added to the Windwos store
[ INFO ](token) Registering certificate
[ INFO ](token) provider: Microsoft Base Smart Card Crypto Provider
[ INFO ](token) container: ba7894c7-6eb6-45c4-b6b6-3bb0deb13a16
[ INFO ](token) Certificate was added to the Windwos store
[ INFO ](pkcs11) No locking functionality is required
[ INFO ](pkcs11) [C_Initialize] = 0x00000000
[ INFO ](pkcs11) [C_GetInfo]
[ INFO ](pkcs11) [C_GetInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Adding newly detected reader Gemplus USB SmartCard Reader 0
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Creating slot 0 for reader Gemplus USB SmartCard Reader 0
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](pkcs11) Found supported card. Will try to load the token
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ WARN ](pcsc) SCardConnect           RV = 0x8010000b
[ WARN ](pcsc) SCardConnect           RV = 0x8010000b
[ INFO ](token) Loading token
[ INFO ](token) Seeding token's RNG using card as entropy pool
[ INFO ](token) RNG seeded by using 32 bytes of entropy.
[ WARN ](card) Select failed
[ INFO ](token) EF.DIR: [{"SSCD" OID = 'A0:00:00:00:63:50:4B:43:53:2D:31:35' at 3F00DF02}, {"ICAO" OID = 'A0:00:00:02:47:10:01' at 3F00DF01}]
[ INFO ](token) EF.DIR SSCD entry: {"SSCD" OID = 'A0:00:00:00:63:50:4B:43:53:2D:31:35' at 3F00DF02}
[ INFO ](token) EF.DIR ICAO entry: {"ICAO" OID = 'A0:00:00:02:47:10:01' at 3F00DF01}
[ INFO ](card) Read 82 bytes file.
[ INFO ](token) EF.CardAccess: Card access [PaceInfo(0.4.0.127.0.7.2.2.4.2.1, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.2, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.3, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.4, V2, param id = 13)]
[ INFO ](pkcs11) This token is not authenticated and requires initial authentication. Will try to look in cache for it's CAN.
[ INFO ](ipc) Opening client memory segment
[ INFO ](ipc) Looking for cache object
[ INFO ](ipc) Constructed cache
[ INFO ](pkcs11) Cache entry for reader found (6 bytes).
[ INFO ](card) Preparing to peform PACE
[ INFO ](card) Preparing PACE environment for key ref 2 (CAN)
[ INFO ](card) PACE done with key ref 2
[ INFO ](card) Read 56 bytes file.
[ WARN ](token) Failed to parse file 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[ INFO ](token) EF.OD: []
[ INFO ](token) Assuming default EF.OD
[ INFO ](card) Read 8 bytes file.
[ WARN ](token) Failed to parse file 0000000000000000
[ INFO ](token) EF.CiaInfo: { manufacturer = "", label = "", serial number = }
[ INFO ](card) Read 92 bytes file.
[ INFO ](pkcs11) Detected private key to be 256 bit long.
[ INFO ](card) Read 92 bytes file.
[ INFO ](pkcs11) Detected private key to be 256 bit long.
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotInfo]
[ INFO ](pkcs11) [C_GetSlotInfo] = 0x00000000
[ WARN ](pkcs11) [C_Initialize] = 0x00000191 
[ INFO ](pkcs11) [C_GetInfo]
[ INFO ](pkcs11) [C_GetInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotInfo]
[ INFO ](pkcs11) [C_GetSlotInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](pkcs11) [C_OpenSession]
[ INFO ](pkcs11) Creating session 1024
[ INFO ](pkcs11) [C_OpenSession] = 0x00000000
[ INFO ](pkcs11) [C_GetSessionInfo]
[ INFO ](pkcs11) Session state = 0 flags: 6
[ INFO ](pkcs11) [C_GetSessionInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotInfo]
[ INFO ](pkcs11) [C_GetSlotInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetMechanismList]
[ INFO ](pkcs11) [C_GetMechanismList] = 0x00000000
[ INFO ](pkcs11) [C_GetMechanismList]
[ INFO ](pkcs11) [C_GetMechanismList] = 0x00000000
[ INFO ](pkcs11) [C_GetMechanismInfo]
[ INFO ](pkcs11) [C_GetMechanismInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetMechanismInfo]
[ INFO ](pkcs11) [C_GetMechanismInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetMechanismInfo]
[ INFO ](pkcs11) [C_GetMechanismInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetTokenInfo]
[ INFO ](pkcs11) Token flags: 40f
[ INFO ](pkcs11) [C_GetTokenInfo] = 0x00000000
[ INFO ](token) Certificate was removed from the Windwos store
[ INFO ](token) Certificate was removed from the Windwos store
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](token) Loading token
[ INFO ](token) Seeding token's RNG using card as entropy pool
[ INFO ](token) RNG seeded by using 32 bytes of entropy.
[ WARN ](card) Select failed
[ INFO ](token) EF.DIR: [{"SSCD" OID = 'A0:00:00:00:63:50:4B:43:53:2D:31:35' at 3F00DF02}, {"ICAO" OID = 'A0:00:00:02:47:10:01' at 3F00DF01}]
[ INFO ](token) EF.DIR SSCD entry: {"SSCD" OID = 'A0:00:00:00:63:50:4B:43:53:2D:31:35' at 3F00DF02}
[ INFO ](token) EF.DIR ICAO entry: {"ICAO" OID = 'A0:00:00:02:47:10:01' at 3F00DF01}
[ INFO ](card) Read 82 bytes file.
[ INFO ](token) EF.CardAccess: Card access [PaceInfo(0.4.0.127.0.7.2.2.4.2.1, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.2, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.3, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.4, V2, param id = 13)]
[ INFO ](card) Preparing to peform PACE
[ INFO ](card) Preparing PACE environment for key ref 2 (CAN)
[ WARN ](pkcs11) [C_Initialize] = 0x00000191 
[ INFO ](pkcs11) [C_GetInfo]
[ INFO ](pkcs11) [C_GetInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ WARN ](pcsc) SCardStatus            RV = 0x80100069
[ INFO ](pcsc) Detected card change in reader Gemplus USB SmartCard Reader 0
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ INFO ](pkcs11) Found supported card. Will try to load the token
[ INFO ](token) Testing ATR: 3B9D188131FC358031C0694D54434F5373020505D3
[ INFO ](token) ATR supported
[ WARN ](pcsc) SCardConnect           RV = 0x8010000b
[ INFO ](card) PACE done with key ref 2
[ INFO ](card) Read 56 bytes file.
[ WARN ](token) Failed to parse file 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[ INFO ](token) EF.OD: []
[ INFO ](token) Assuming default EF.OD
[ INFO ](card) Read 8 bytes file.
[ WARN ](token) Failed to parse file 0000000000000000
[ INFO ](token) EF.CiaInfo: { manufacturer = "", label = "", serial number = }
[ INFO ](card) Read 92 bytes file.
[ INFO ](pkcs11) Detected private key to be 256 bit long.
[ INFO ](card) Read 92 bytes file.
[ INFO ](pkcs11) Detected private key to be 256 bit long.
[ INFO ](card) Read 1225 bytes file.
[ WARN ](pcsc) SCardConnect           RV = 0x8010000b
[ INFO ](card) Read 1250 bytes file.
[ INFO ](token) Registering certificate
[ INFO ](token) provider: Microsoft Base Smart Card Crypto Provider
[ INFO ](token) container: ae6d5874-8e73-420b-9574-fb50e9afed0e
[ INFO ](token) Certificate was added to the Windwos store
[ INFO ](token) Registering certificate
[ INFO ](token) provider: Microsoft Base Smart Card Crypto Provider
[ INFO ](token) container: ba7894c7-6eb6-45c4-b6b6-3bb0deb13a16
[ INFO ](token) Certificate was added to the Windwos store
[ INFO ](token) Loading token
[ INFO ](token) Seeding token's RNG using card as entropy pool
[ INFO ](token) RNG seeded by using 32 bytes of entropy.
[ WARN ](card) Select failed
[ INFO ](token) EF.DIR: [{"SSCD" OID = 'A0:00:00:00:63:50:4B:43:53:2D:31:35' at 3F00DF02}, {"ICAO" OID = 'A0:00:00:02:47:10:01' at 3F00DF01}]
[ INFO ](token) EF.DIR SSCD entry: {"SSCD" OID = 'A0:00:00:00:63:50:4B:43:53:2D:31:35' at 3F00DF02}
[ INFO ](token) EF.DIR ICAO entry: {"ICAO" OID = 'A0:00:00:02:47:10:01' at 3F00DF01}
[ INFO ](card) Read 82 bytes file.
[ INFO ](token) EF.CardAccess: Card access [PaceInfo(0.4.0.127.0.7.2.2.4.2.1, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.2, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.3, V2, param id = 13), PaceInfo(0.4.0.127.0.7.2.2.4.2.4, V2, param id = 13)]
[ INFO ](pkcs11) This token is not authenticated and requires initial authentication. Will try to look in cache for it's CAN.
[ INFO ](pkcs11) Cache entry for reader found (6 bytes).
[ INFO ](card) Preparing to peform PACE
[ INFO ](card) Preparing PACE environment for key ref 2 (CAN)
[ INFO ](card) PACE done with key ref 2
[ INFO ](card) Read 56 bytes file.
[ WARN ](token) Failed to parse file 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[ INFO ](token) EF.OD: []
[ INFO ](token) Assuming default EF.OD
[ INFO ](card) Read 8 bytes file.
[ WARN ](token) Failed to parse file 0000000000000000
[ INFO ](token) EF.CiaInfo: { manufacturer = "", label = "", serial number = }
[ INFO ](card) Read 92 bytes file.
[ INFO ](pkcs11) Detected private key to be 256 bit long.
[ INFO ](card) Read 92 bytes file.
[ INFO ](pkcs11) Detected private key to be 256 bit long.
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotInfo]
[ INFO ](pkcs11) [C_GetSlotInfo] = 0x00000000
[ WARN ](pkcs11) [C_Initialize] = 0x00000191 
[ INFO ](pkcs11) [C_GetInfo]
[ INFO ](pkcs11) [C_GetInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 1 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotInfo]
[ INFO ](pkcs11) [C_GetSlotInfo] = 0x00000000
[ INFO ](pkcs11) [C_FindObjectsInit]
[ WARN ](pkcs11) [C_FindObjectsInit] = 0x00000032 CKR_DEVICE_REMOVED
[ INFO ](pkcs11) [C_FindObjectsInit]
[ WARN ](pkcs11) [C_FindObjectsInit] = 0x000000b3 CKR_SESSION_HANDLE_INVALID
[ INFO ](pkcs11) [C_FindObjectsInit]
[ WARN ](pkcs11) [C_FindObjectsInit] = 0x000000b3 CKR_SESSION_HANDLE_INVALID
[ INFO ](token) Certificate was removed from the Windwos store
[ INFO ](token) Certificate was removed from the Windwos store
[ WARN ](pcsc) SCardGetStatusChange   RV = 0x80100012
[ WARN ](pkcs11) [C_Initialize] = 0x00000191 
[ INFO ](pkcs11) [C_GetInfo]
[ INFO ](pkcs11) [C_GetInfo] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Found removed reader Gemplus USB SmartCard Reader 0
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 0 readers
[ INFO ](pkcs11) Removing slot for removed reader Gemplus USB SmartCard Reader 0
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_GetSlotList]
[ INFO ](pcsc) Looking for readers...
[ INFO ](pcsc) Adding new readers
[ INFO ](pcsc) Returning 0 readers
[ INFO ](pkcs11) Slot list requested. present = true
[ INFO ](pkcs11) [C_GetSlotList] = 0x00000000
[ INFO ](pkcs11) [C_Finalize]
[ WARN ](pcsc) SCardGetStatusChange   RV = 0x80100012
[ INFO ](token) Testing ATR: 3B9813400AA503010101AD1311
[ INFO ](token) ATR unsupported
[ INFO ](token) Testing ATR: 
[ INFO ](token) ATR unsupported
[ WARN ](pcsc) SCardGetStatusChange   RV = 0x80100012
[ WARN ](pcsc) SCardGetStatusChange   RV = 0x80100012
[ WARN ](pcsc) SCardGetStatusChange   RV = 0x80100002
```

**Comment by Ottunger** [comment]
Solved by adding PKCS15 layer in our Fortify
