### ISSUE TITLE
SafeNet eToken 5100/5110 crash Fortify on MacOS

### ISSUE THREAD

**Issue by cmjunior** [PeculiarVentures/fortify#483]
I'm trying to use an USB Gemalto Safenet token, on my MacOS within Fortify, but, with the Fortify opened, when I connect the usb device, Fortify just closes. If I try to open fortify with the token already connected, It also closes.

I'd tried to configure the token on cards.json, as follow:

`    {
      "atr": "3BD518008131FE7D8073C82110F4",
      "name": "SafeNet eToken 5100",
      "driver": "39b3d7a3662c4b48bb120d008dd18648"
    },
    {
      "atr": "3BD5180081313A7D8073C8211030",
      "name": "SafeNet eToken 5110",
      "driver": "39b3d7a3662c4b48bb120d008dd18648"
    },

...

    {
      "id": "3bd518008131fe7d8073c82110f4",
      "name": "SafeNet eToken",
      "file": {
        "windows": "%WINDIR/System32/eToken.dll",
        "osx": "/Library/Frameworks/eToken.framework/Versions/A/libeToken.dylib"
      }
    },
`

I also tried some variations on OSX library, when this files came with the software provided by the company who sell the token, I'll attach a print of these files:

<img width="763" alt="Captura de Tela 2022-04-08 às 10 30 48" src="https://user-images.githubusercontent.com/1102837/162445765-151ea7f0-7057-4fd8-81fc-212eadb9c134.png">

I configured the Fortify to store logs, but It does not contains any error, as can be seen below.

`{"source":"application","time":"2022-04-08T13:33:45.684Z","level":"info","message":"Starting","timestamp":"2022-04-08T13:33:45.687Z"}
{"source":"application","version":"1.8.3","versionChrome":"87.0.4280.141","versionElectron":"11.5.0","versionNode":"12.18.3","level":"info","message":"Application info","timestamp":"2022-04-08T13:33:45.701Z"}
{"source":"system","type":"Darwin","platform":"darwin","arch":"x64","cpus":8,"version":"11.6.5","totalmem":17179869184,"freemem":295075840,"level":"info","message":"System info","timestamp":"2022-04-08T13:33:45.702Z"}
{"source":"firefox-providers","dir":"/Users/cmjr/Library/Application Support/Firefox/Profiles","level":"info","message":"Provider does not exist","timestamp":"2022-04-08T13:33:45.703Z"}
{"source":"system","width":1920,"height":1200,"level":"info","message":"Screen size","timestamp":"2022-04-08T13:33:45.772Z"}
{"source":"l10n","lang":"pt","level":"info","message":"Change language","timestamp":"2022-04-08T13:33:45.773Z"}
{"source":"ssl-service","status":"valid","level":"info","message":"Get certificate status","timestamp":"2022-04-08T13:33:45.810Z"}
{"source":"firefox","path":"/Users/cmjr/Library/Application Support/Firefox/Profiles","level":"info","message":"Profiles folder does not exist","timestamp":"2022-04-08T13:33:45.811Z"}
{"source":"server","level":"info","message":"SSL certificate is loaded","timestamp":"2022-04-08T13:33:45.812Z"}
{"source":"server","level":"info","message":"Comparing current version of card.json file with remote","timestamp":"2022-04-08T13:33:45.814Z"}
{"source":"server","version":"1.1.7","level":"info","message":"card.json has the latest version","timestamp":"2022-04-08T13:33:46.176Z"}
{"source":"pcsc","level":"info","message":"Start PCSC listening","timestamp":"2022-04-08T13:33:46.300Z"}
{"source":"update","level":"info","message":"Check for new update","timestamp":"2022-04-08T13:33:46.316Z"}
{"source":"application","time":"2022-04-08T13:33:46.317Z","duration":633,"level":"info","message":"Loaded","timestamp":"2022-04-08T13:33:46.317Z"}
{"source":"server","address":"127.0.0.1:31337","level":"info","message":"Started","timestamp":"2022-04-08T13:33:46.319Z"}
{"source":"provider","library":"/Applications/Fortify.app/Contents/Resources/app/libpvpkcs11.dylib","manufacturerId":"Module","cryptokiVersion":{"major":2,"minor":30},"libraryVersion":{"major":1,"minor":2},"firmwareVersion":{"major":0,"minor":1},"level":"info","message":"PKCS#11 library information","timestamp":"2022-04-08T13:33:46.361Z"}
{"source":"provider","id":"97f0ba8cbe75b37931eb6dd0ac05959a98e3c777","library":"/Applications/Fortify.app/Contents/Resources/app/libpvpkcs11.dylib","name":"MacOS Crypto","reader":"MacOS Crypto","level":"info","message":"Crypto provider was added to the list","timestamp":"2022-04-08T13:33:46.362Z"}
{"source":"pcsc","level":"info","message":"Start PCSC listening","timestamp":"2022-04-08T13:33:46.365Z"}
{"source":"pcsc","reader":"SafeNet eToken 5100","level":"info","message":"Initialize new reader","timestamp":"2022-04-08T13:33:46.368Z"}
{"source":"pcsc","reader":"SafeNet eToken 5100","level":"info","message":"Initialize new reader","timestamp":"2022-04-08T13:33:46.369Z"}
{"source":"pcsc","reader":"SafeNet eToken 5100","atr":"3bd518008131fe7d8073c82110f4","level":"info","message":"New token was added to the reader","timestamp":"2022-04-08T13:33:46.371Z"}
{"source":"pcsc","reader":"SafeNet eToken 5100","atr":"3bd518008131fe7d8073c82110f4","level":"info","message":"New token was added to the reader","timestamp":"2022-04-08T13:33:46.372Z"}
{"source":"update","level":"info","message":"New version wasn't found","timestamp":"2022-04-08T13:33:46.537Z"}
{"source":"provider","reader":"SafeNet eToken 5100","name":"SafeNet eToken 5100","atr":"3bd518008131fe7d8073c82110f4","level":"info","message":"Token was added to the reader","timestamp":"2022-04-08T13:33:48.428Z"}`

**Comment by microshine** [comment]
Do you use SafeNET Authentication Clint? What is your version. I'm using V10.8. It works fine with my SafeNET 5110 token

**Comment by cmjunior** [comment]
> Do you use SafeNET Authentication Clint? What is your version. I'm using V10.8. It works fine with my SafeNET 5110 token

I'm have this software, it was the software the cert provider recommended to us. In fact, the library files I'm trying to put on cards.json, came with this software.

How's your cards.json?

**Comment by jonathanchagas** [comment]
Put the PKCS11 dylib on card.json, it may work.

**Comment by cmjunior** [comment]
Hey guys, sorry for the late answer but. It kind of worked, I'd installed the SafeNET Authentication Client v10.8 and It's nothing crashing anymore.

But, my certificate does not show on the list, the list of available certificates include a lot of Apple Development certificates, there's a way to filter this? Or to remove them to see if my A3 shows up?

**Comment by rmhrisk** [comment]
It’s unclear which “list” your referring to.

I am not sure what “A3” is.

If logging is enabled you can see all interactions, including what P11 libraries are loaded for which tokens and what certificates are found on token.

**Comment by cmjunior** [comment]
What I'm saying about my fortify showing only Mac OS keys, is like in the screenshot, below: 

<img width="485" alt="certificates-on-fortify" src="https://user-images.githubusercontent.com/1102837/164227362-a8af62d7-a1ba-4293-8e55-2af32f15c464.png">

Then in the fortify logs, below, when fortify call: certStorage/keys, the listed certificates are only these MAC OS Crypto, keys.

`// THESE LOGS ARE SHOWN WHEN I OPEN FORTIFY

{"source":"application","time":"2022-04-14T13:27:00.399Z","level":"info","message":"Starting","timestamp":"2022-04-14T13:27:00.403Z"}
{"source":"application","version":"1.8.3","versionChrome":"87.0.4280.141","versionElectron":"11.5.0","versionNode":"12.18.3","level":"info","message":"Application info","timestamp":"2022-04-14T13:27:00.417Z"}
{"source":"system","type":"Darwin","platform":"darwin","arch":"x64","cpus":8,"version":"11.6.5","totalmem":17179869184,"freemem":118681600,"level":"info","message":"System info","timestamp":"2022-04-14T13:27:00.418Z"}
{"source":"firefox-providers","dir":"/Users/cmjr/Library/Application Support/Firefox/Profiles","level":"info","message":"Provider does not exist","timestamp":"2022-04-14T13:27:00.419Z"}
{"source":"system","width":1920,"height":1200,"level":"info","message":"Screen size","timestamp":"2022-04-14T13:27:00.501Z"}
{"source":"l10n","lang":"pt","level":"info","message":"Change language","timestamp":"2022-04-14T13:27:00.503Z"}
{"source":"ssl-service","status":"valid","level":"info","message":"Get certificate status","timestamp":"2022-04-14T13:27:00.541Z"}
{"source":"firefox","path":"/Users/cmjr/Library/Application Support/Firefox/Profiles","level":"info","message":"Profiles folder does not exist","timestamp":"2022-04-14T13:27:00.542Z"}
{"source":"server","level":"info","message":"SSL certificate is loaded","timestamp":"2022-04-14T13:27:00.543Z"}
{"source":"server","level":"info","message":"Comparing current version of card.json file with remote","timestamp":"2022-04-14T13:27:00.544Z"}
{"source":"server","version":"1.1.7","level":"info","message":"card.json has the latest version","timestamp":"2022-04-14T13:27:00.905Z"}
{"source":"pcsc","level":"info","message":"Start PCSC listening","timestamp":"2022-04-14T13:27:01.020Z"}
{"source":"update","level":"info","message":"Check for new update","timestamp":"2022-04-14T13:27:01.037Z"}
{"source":"application","time":"2022-04-14T13:27:01.038Z","duration":639,"level":"info","message":"Loaded","timestamp":"2022-04-14T13:27:01.039Z"}
{"source":"server","address":"127.0.0.1:31337","level":"info","message":"Started","timestamp":"2022-04-14T13:27:01.041Z"}
{"source":"provider","library":"/Applications/Fortify.app/Contents/Resources/app/libpvpkcs11.dylib","manufacturerId":"Module","cryptokiVersion":{"major":2,"minor":30},"libraryVersion":{"major":1,"minor":2},"firmwareVersion":{"major":0,"minor":1},"level":"info","message":"PKCS#11 library information","timestamp":"2022-04-14T13:27:01.083Z"}
{"source":"provider","id":"0a43b07aaefa4f6869daf42a741477127eff620d","library":"/Applications/Fortify.app/Contents/Resources/app/libpvpkcs11.dylib","name":"MacOS Crypto","reader":"MacOS Crypto","level":"info","message":"Crypto provider was added to the list","timestamp":"2022-04-14T13:27:01.084Z"}
{"source":"server","level":"error","message":"Server event error","timestamp":"2022-04-14T13:27:01.089Z"}
{"source":"server","level":"error","message":"Server event error","timestamp":"2022-04-14T13:27:01.090Z"}
{"source":"pcsc","level":"info","message":"Start PCSC listening","timestamp":"2022-04-14T13:27:01.091Z"}
{"source":"pcsc","reader":"SafeNet eToken 5100","level":"info","message":"Initialize new reader","timestamp":"2022-04-14T13:27:01.094Z"}
{"source":"pcsc","reader":"SafeNet eToken 5100","level":"info","message":"Initialize new reader","timestamp":"2022-04-14T13:27:01.095Z"}
{"source":"pcsc","reader":"SafeNet eToken 5100","atr":"3bd518008131fe7d8073c82110f4","level":"info","message":"New token was added to the reader","timestamp":"2022-04-14T13:27:01.097Z"}
{"source":"pcsc","reader":"SafeNet eToken 5100","atr":"3bd518008131fe7d8073c82110f4","level":"info","message":"New token was added to the reader","timestamp":"2022-04-14T13:27:01.098Z"}
{"source":"update","level":"info","message":"New version wasn't found","timestamp":"2022-04-14T13:27:01.122Z"}
{"source":"server","reader":"SafeNet eToken 5100","atr":"3bd518008131fe7d8073c82110f4","level":"info","message":"New token was found reader","timestamp":"2022-04-14T13:27:03.136Z"}
{"source":"windows","id":"question.new.token","level":"info","message":"Don't show dialog It's disabled","timestamp":"2022-04-14T13:27:03.138Z"}
{"source":"server","error":"'question.new.token' window disabled","stack":"Error: 'question.new.token' window disabled\n    
at /Applications/Fortify.app/Contents/Resources/app/out/main.js:256:113640\n
at new Promise (<anonymous>)\n    
at u.showTokenWindow (/Applications/Fortify.app/Contents/Resources/app/out/main.js:256:113356)\n    
at uc.<anonymous> (/Applications/Fortify.app/Contents/Resources/app/out/main.js:31:554179)\n    
at uc.emit (events.js:315:20)\n    
at uc.emit (/Applications/Fortify.app/Contents/Resources/app/out/main.js:256:224088)\n    
at cc.<anonymous> (/Applications/Fortify.app/Contents/Resources/app/out/main.js:281:134445)\n    
at cc.emit (events.js:315:20)\n    
at cc.emit (/Applications/Fortify.app/Contents/Resources/app/out/main.js:256:224088)\n    
at cc.emit (/Applications/Fortify.app/Contents/Resources/app/out/main.js:281:102210)","level":"error","message":"Token window","timestamp":"2022-04-14T13:27:03.141Z"}`

I'd noticed an error on it...

And below is the logs when the fortify list the keys:
<img width="1527" alt="Captura de Tela 2022-04-20 às 09 17 42" src="https://user-images.githubusercontent.com/1102837/164228612-fd5540a3-4e77-4e8b-8673-d7eaf6b5a784.png">

I don't see my USB Token A3 certificate on the list, that is the certificate in the SafeNet Token, the one you can see on the other screenshot, as "MARIA JOSE GALVAO..."

![certificates-on-chrome](https://user-images.githubusercontent.com/1102837/164229038-866e6022-8e5f-4f34-a5b8-c2fa4449de91.jpg)

I'm not sure how can I show this certificate, inside USB token, on fortify

**Comment by microshine** [comment]
> But, my certificate does not show on the list, the list of available certificates include a lot of Apple Development certificates, there's a way to filter this? Or to remove them to see if my A3 shows up?

Do you see SafeNet Provider in the select controller?

It's strange, but I don't see any logs of SafeNET PKCS#11 lib loading. Please remove `~/.fortify/card.json` file and restart the Fortify application. It must download the latest version of card.json file
