### ISSUE TITLE
Socket connection is not open

### ISSUE THREAD

**Issue by KINFOO** [PeculiarVentures/fortify#488]
# Configuration

Fortify: `1.8.3`
Firefox: `78.15.0esr`
OS: Debian GNU/Linux 11
YubiKey 5 NFC

# Context

I manage to sign text using example https://fortifyapp.com/examples/signing
I want to integrate this in a react application using fortify-webcomponents-react `0.2.37`
I get a `Socket connection is not open` running this code
```jsx
const OperationsAuthorizeContainer = () => {
  const classes = useStyles();
  const [text, setText] = useState('');
  const [authorized, setAuthorized] = useState(false);
  const handleContinue = async (event: any) => {
    setAuthorized(true);
    setText(event.detail.providerId);
    try {
      let provider = await event.detail.server.getCrypto(event.detail.providerId);
      provider.sign = provider.subtle.sign.bind(provider.subtle);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Grid container spacing={4} alignItems="stretch" className={classes.container}>
        {!authorized ? (
          <>
            <Grid item xs={2}></Grid>
            <Grid item xs={8}>
              <PeculiarFortifyCertificates
                hide-footer
                filters={{ onlySmartcards: true, onlyWithPrivateKey: true, keyUsage: ['digitalSignature'] }}
                onContinue={handleContinue}
                onCancel={() => alert('Very well, but cancel what?')}
              />
            </Grid>
          </>
        ) : (
          <>
            <Grid item xs={6}>
              <div className={classes.widget}>
                <TextField
                  id="filled-textarea"
                  label="Text to sign"
                  placeholder="Type text to sign"
                  multiline
                  fullWidth
                  variant="filled"
                  onChange={(e) => setText(e.target.value)}
                />
              </div>
            </Grid>
            <Grid item xs={6}>
              <div className={classes.widget}>
                <h3>Signed text:</h3>
                <span>{text}</span>
              </div>
            </Grid>
          </>
        )}
      </Grid>
    </>
  );
};
```

Error is raised by this line
```js
let provider = await event.detail.server.getCrypto(event.detail.providerId);
```

What am I doing wrong?
It is a subset of the code provided by example...

**Comment by KINFOO** [comment]
Hi,

I tried pre-release [1.8.4](https://github.com/PeculiarVentures/fortify/releases/tag/1.8.4) version and got `SEC_ERROR_BAD_DATABASE` as soon as I insert _Yubikey_

```
error: [ssl-installer]  SSL install error {"error":"Command failed: \"certutil\" -L -d \"sql:/home/kevin/.mozilla/firefox/Crash Reports\" -h \"all\"\ncertutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.\n","stack":"Error: Command failed: \"certutil\" -L -d \"sql:/home/kevin/.mozilla/firefox/Crash Reports\" -h \"all\"\ncertutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.\n\n    at checkExecSyncError (child_process.js:625:11)\n    at Object.execSync (child_process.js:661:15)\n    at Object.execSync (electron/js2c/asar_bundle.js:5:12288)\n    at t.NssCertUtils.run (/opt/Fortify/resources/app.asar/out/main.js:256:182457)\n    at t.NssCertUtils.list (/opt/Fortify/resources/app.asar/out/main.js:256:181905)\n    at t.NssCertUtils.exists (/opt/Fortify/resources/app.asar/out/main.js:256:181646)\n    at t.SslCertInstaller.installFirefox (/opt/Fortify/resources/app.asar/out/main.js:256:179862)\n    at g.run (/opt/Fortify/resources/app.asar/out/main.js:256:175384)\n    at t.Server.init (/opt/Fortify/resources/app.asar/out/main.js:31:553306)\n    at b.initServer (/opt/Fortify/resources/app.asar/out/main.js:172:90344)"}
```

**Comment by davidbonnet** [comment]
The example above eagerly unmounted the `PeculiarFortifyCertificates` component during the `onContinue` callback execution. Thus there is no particular bug.

As a suggestion though, it would be interesting to extract the logic that lists certificates and selects one so that it becomes UI library/framework agnostic and thus becomes easier to test/integrate.
