### ISSUE TITLE
Need to check in logged in and if not trigger log-in on create CSR page.

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/fortify#61]
![image](https://user-images.githubusercontent.com/1619279/30998754-b02dff78-a485-11e7-9c1d-8f0d50b04d99.png)

```
{"level":"error","message":"Error: Rsa: Can not generate new key\nCKR_USER_NOT_LOGGED_IN:257\n    at Error (native) C_GenerateKeyPair:899\n    at new WebCryptoError (/Applications/Fortify.app/Contents/Resources/app/node_modules/webcrypto-core/dist/webcrypto-core.js:36:21)\n    at /Applications/Fortify.app/Contents/Resources/app/node_modules/node-webcrypto-p11/built/crypto/rsa.js:81:36\n    at /Applications/Fortify.app/Contents/Resources/app/node_modules/graphene-pk11/build/session.js:178:25","timestamp":"2017-09-29T02:45:43.759Z"}
```

**Comment by donskov** [comment]
fixed
