### ISSUE TITLE
Unable to sign with certificate and key on YubiKey 4

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/fortify#93]
I created a self-signed certificate manually using the YubiKey software:

When I try to sign with that in Hancock I get:
![image](https://user-images.githubusercontent.com/1619279/33512280-def195fc-d6e1-11e7-98b3-83eae8cc84c2.png)

```
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 provider/action/info","timestamp":"2017-12-02T05:54:45.629Z"}
{"level":"info","message":"Server: Close session Socket Error: read ECONNRESET (code: 1006)","timestamp":"2017-12-02T05:54:55.331Z"}
{"level":"info","message":"Server: Close session Socket Error: read ECONNRESET (code: 1006)","timestamp":"2017-12-02T05:54:55.332Z"}
{"level":"info","message":"Server: New session connect 127.0.0.1","timestamp":"2017-12-02T05:55:03.088Z"}
{"level":"info","message":"Server: Push session to stack","timestamp":"2017-12-02T05:55:03.088Z"}
{"level":"info","message":"Cannot parse MessageSignedProtocol","timestamp":"2017-12-02T05:55:03.172Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 server/isLoggedIn","timestamp":"2017-12-02T05:55:03.209Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 provider/action/info","timestamp":"2017-12-02T05:55:03.258Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 provider/action/getCrypto","timestamp":"2017-12-02T05:55:03.286Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/isLoggedIn","timestamp":"2017-12-02T05:55:03.307Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/certificateStorage/keys","timestamp":"2017-12-02T05:55:03.324Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/keyStorage/keys","timestamp":"2017-12-02T05:55:03.364Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/certificateStorage/getItem","timestamp":"2017-12-02T05:55:03.391Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/certificateStorage/export","timestamp":"2017-12-02T05:55:03.461Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/certificateStorage/getItem","timestamp":"2017-12-02T05:55:03.517Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/certificateStorage/export","timestamp":"2017-12-02T05:55:03.572Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 provider/action/getCrypto","timestamp":"2017-12-02T05:55:03.621Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/isLoggedIn","timestamp":"2017-12-02T05:55:03.645Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/certificateStorage/keys","timestamp":"2017-12-02T05:55:03.660Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/keyStorage/keys","timestamp":"2017-12-02T05:55:03.677Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/certificateStorage/getItem","timestamp":"2017-12-02T05:55:03.692Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/certificateStorage/export","timestamp":"2017-12-02T05:55:03.713Z"}
{"level":"info","message":"Server: New session connect 127.0.0.1","timestamp":"2017-12-02T05:55:07.248Z"}
{"level":"info","message":"Server: Push session to stack","timestamp":"2017-12-02T05:55:07.249Z"}
{"level":"info","message":"Cannot parse MessageSignedProtocol","timestamp":"2017-12-02T05:55:07.285Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 provider/action/getCrypto","timestamp":"2017-12-02T05:55:07.305Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/certificateStorage/getItem","timestamp":"2017-12-02T05:55:07.322Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/certificateStorage/export","timestamp":"2017-12-02T05:55:07.354Z"}
{"level":"info","message":"Server: session:1ce32ca133394ffa2e08c046531f6836f165e5621c56b3b0a8f246217cafb436 crypto/subtle/importKey","timestamp":"2017-12-02T05:55:07.371Z"}
{"level":"error","message":"Error: CKR_ARGUMENTS_BAD:7\n    at Error (native) C_CreateObject:473\n    at Session.create (/Applications/Fortify.app/Contents/Resources/app/node_modules/graphene-pk11/build/session.js:61:32)\n    at /Applications/Fortify.app/Contents/Resources/app/node_modules/node-webcrypto-p11/built/crypto/rsa.js:253:34\n    at Promise (<anonymous>)\n    at Function.RsaCrypto.importJwkPublicKey (/Applications/Fortify.app/Contents/Resources/app/node_modules/node-webcrypto-p11/built/crypto/rsa.js:249:16)\n    at /Applications/Fortify.app/Contents/Resources/app/node_modules/node-webcrypto-p11/built/crypto/rsa.js:162:34\n    at <anonymous>","timestamp":"2017-12-02T05:55:07.376Z"}```

**Comment by rmhrisk** [comment]
Fixed
